### ISSUE TITLE
dollar conversion from real exchanges

### ISSUE THREAD

**Issue by lucaszanella** [Jaxx-io/Jaxx#1]
Hi, the dollar conversion for BRL is innacurate, because exchanges won't trade at this value in my country, neither credit card will charge at that price, so I'd suggest, at least for BRL, to use the price from mercadobitcoin.com.br and foxbit.exchange, otherwise it has no point in using showing the price in another currency.

**Comment by chrisforrester** [comment]
thanks for the heads up lucas :)
