### ISSUE TITLE
Jaxx OSX

### ISSUE THREAD

**Issue by Atalantia** [Jaxx-io/Jaxx#10]
Yes, it works so so. But its not really good. The menus are incomplete. For an app like this, confirmation when quitting is not required. It is way to big regards to is functionality. The folder /Applications/Jaxx.app/Contents/Frameworks/Electron Framework.framework/Versions can be deleted and it still works but its about 150mB smaller.

**Comment by JaiKarta** [comment]
I’m using it right now, and it’s frozen.  I tried the shapeshift program , but doesn’t seem to be working either.  I tried to send and did not process.  Knowing that it’s a big rush to etherium today, maybe there is a back up.
