### ISSUE TITLE
Send BTC: Cannot enter enough digits in amount field

### ISSUE THREAD

**Issue by pinheadmz** [Jaxx-io/Jaxx#12]
Chrome extension Version 1.2.25
Chrome Version 60.0.3112.101
OSX

The wallet does not allow me to enter more than 8 characters. As I type a 9th character it appears for a moment then is deleted. Some Bitcoin merchants expect a specific transaction amount like 0.01016148 which I can not even type into the wallet! Even leaving off the first 0 is insufficient because the decimal point itself occupies a space, best I can do is send .0101615 -- exactly 8 characters. Now I'm going to have 2 extra satoshis in my account, forever... If I was spending 10 or more BTC I'd be forced to reduce amount resolution even more.

**Comment by jaxxThageesan** [comment]
@pinheadmz bitcoin only has 8 decimal places so you should be able to send all your satoshis.
