### ISSUE TITLE
auto-updated 1.3.4 app errors on launch and won't start

### ISSUE THREAD

**Issue by jakeonfire** [Jaxx-io/Jaxx#15]
after auto-update on restart of version 1.3.3 downloaded from jaxx.io the new version will not start, and instead shows an error pop-up:
<img width="421" alt="screen shot 2017-11-10 at 11 32 53 pm" src="https://user-images.githubusercontent.com/68826/32687400-1497627c-c670-11e7-8e88-500b48d2603e.png">
The error looks like a `git` merge conflict (possibly the merge conflict was committed to master without being resolved...).

**Comment by aphex13** [comment]
got the same error

**Comment by abelvargas** [comment]
OSX 10.13 High Sierra. Same error.

**Comment by allpratik** [comment]
When can we expect to have resolution for this? I want to have an immediate access to my funds and now locked out due to this very error. 
I'm on High Sierra, right now.

**Comment by aphex13** [comment]
@allpratik try to update to 1.3.7 -> this version is working for me. (high sierra 10.13.1, jaxx 1.3.7)

**Comment by allpratik** [comment]
Thank you @aphex13 ! V 1.3.7 did worked for me.
