### ISSUE TITLE
Lost Wallet on Jaxx update to 1.3

### ISSUE THREAD

**Issue by xistoso** [Jaxx-io/Jaxx#18]
On update from version 1.2  to 1.3 jaxx was initializing wallet with old adress when my PC went down. Now i only have the option to create new wallet or restore from 12 digits. Any one encontered the same problem?

**Comment by jaxxThageesan** [comment]
@xistoso Sorry for the late response.  If you are still having an issue with this please submit a support request (https://decentral.zendesk.com/hc/en-us/requests/new) and we will look into it.
