### ISSUE TITLE
Jaxx BTC Wallet Address shows a 0 balance on blockchain.info

### ISSUE THREAD

**Issue by AlvaroLuken** [Jaxx-io/Jaxx#21]
<img width="1267" alt="screen shot 2018-03-03 at 9 36 17 pm" src="https://user-images.githubusercontent.com/25407127/36941513-06a83574-1f2b-11e8-9aca-9125867bb573.png">

I have a balance of a few hundred bucks on it and have made many transactions with it in the past.

Using latest version of Jaxx MacOSX desktop.

**Comment by jaxxThageesan** [comment]
@AlvaroLuken The best way to get support on this issue is contacting our support team at https://decentral.zendesk.com/hc/en-us/requests/new.
