### ISSUE TITLE
The real about a Jaxx Vulnerability

### ISSUE THREAD

**Issue by bitsnaps** [Jaxx-io/Jaxx#22]
Hi,
We've seen what seems to be a serious vulnerability about jaxx, since the full source is not available, how can someone audit if this is due to an issue with security model of jaxx or some user's bad practice:
https://www.ccn.com/users-report-losing-400000-due-to-jaxx-wallet-vulnerability/
any security updates since there?

**Comment by epimazzo** [comment]
Hey,
Interesting as I also submitted to support days ago a flaw found last year around the mnemonic phrase which expose your private keys. They replied me with their URL blog mentioning how they deal with security breach which is not the issue I reported. So, no clues yet.

**Comment by kenorb** [comment]
Related:
- GH-6
- [Extracting the Jaxx 12-word wallet backup phrase](https://vxlabs.com/2017/06/10/extracting-the-jaxx-12-word-wallet-backup-phrase/)

**Comment by jaxxThageesan** [comment]
This issue has been solved in Jaxx Liberty.  Visit https://jaxx.io/ to learn more.  If you have any further questions regarding this topic visit https://support.decentral.ca/hc/en-us.
