### ISSUE TITLE
Support to XMR (Monero).

### ISSUE THREAD

**Issue by dyorgio** [Jaxx-io/Jaxx#24]
Please add support to Monero coin, it is in 13th on market share according with https://coinmarketcap.com (2018-07-18).

<img width="1198" alt="captura de tela 2018-07-18 as 10 47 13" src="https://user-images.githubusercontent.com/1438251/42885696-0df5fac4-8a78-11e8-8aac-17e6d9b82598.png">

**Comment by jaxxThageesan** [comment]
@dyorgio Send your request to the business development team. Here is the email BD@Decentral.ca
