### ISSUE TITLE
Segmentation fault with glibc-2.28

### ISSUE THREAD

**Issue by target111** [Jaxx-io/Jaxx#25]
Hi there,

Jaxx doesn't seem to be working with glibc-2.28 and retruns seg fault. Here is the ouput from an strace:
`stat("/etc/gnutls/default-priorities", 0x7fff361dcf00) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0xb7d420} ---
+++ killed by SIGSEGV +++
Segmentation fault
`

**Comment by AnikGhosh** [comment]
Hello @target111 ! We do not offer support via GitHub or maintain the issues reported here. Please open a support ticket at https://support.decentral.ca/hc/en-us/requests/new and our User Success Team will help you out. Cheers!
Please note that Jaxx and Jaxx Liberty is **not** open sourced.
