### ISSUE TITLE
jaxx TX-018 error

### ISSUE THREAD

**Issue by Roddy1219** [Jaxx-io/Jaxx#26]
Hello，Jaxx:
      I used jaxx Liberty wallet to send DogeCoin, Echo error info TX-018 Transaction Failed.

**Comment by AnikGhosh** [comment]
Hello @Roddy1219! Sorry to hear the issue you're experiencing. We do not offer support via GitHub or maintain the issues reported here. Please open a support ticket at https://support.decentral.ca/hc/en-us/requests/new and our User Success Team will help you out. Cheers!
Please note that Jaxx or Jaxx Liberty is **not** open sourced.
