### ISSUE TITLE
[Ubuntu] Jaxx window overflows screen height, no scroll, no resize available

### ISSUE THREAD

**Issue by DarthVanger** [Jaxx-io/Jaxx#27]
```
jaxx version: com.liberty.jaxx-2.0.6-x86_64.AppImage 
sha1sum: d01b78183e58d1e9275cb7740445e691a9460f93
```

I can't use `Jaxx Liberty` on `Ubuntu 18.04`, because its window is overflowing the screen height, no scroll available and window resize doesn't work. So I just don't have a way to get down to the button, to accept the service terms.

Screenshots:
![jaxx-liberty2](https://user-images.githubusercontent.com/6686679/48299671-e8868900-e4d8-11e8-96e0-aacc91e5a9c0.jpg)

![jaxx-liberty](https://user-images.githubusercontent.com/6686679/48299609-1fa86a80-e4d8-11e8-92f9-a357bd6ad9f6.jpg)

My screen resolution is `1366x768` as reported by https://whatismyresolution.com/
I'm using 15.6 inches laptop.

**Comment by AnikGhosh** [comment]
Hello @DarthVanger ! Sorry to hear the issue you're experiencing. We do not offer support via GitHub or maintain the issues reported here. Please open a support ticket at https://support.decentral.ca/hc/en-us/requests/new and our User Success Team will help you out. Cheers!
Please note that Jaxx or Jaxx Liberty is **not** open sourced.
