### ISSUE TITLE
Gas price 5e-8 ether

### ISSUE THREAD

**Issue by RCasatta** [Jaxx-io/Jaxx#4]
transaction are generated with a default gas price 5e-8 ether
most of the network is currently accepting transaction at 2e-8 ether which is 2.5x times cheaper.
If you want to keep 5e-8 as default, could you implement a way of changing it from the preferences?

**Comment by psionic81** [comment]
We're looking into these forms of network optimization in the 1.0 release. 21,000 gas limit * 50 gWei = 1050000000000000 wei is around $0.000223923 US right now, so you'd have to do 50 transactions per cent cost.

Obviously contract execution can get way more expensive however.  We'll contract our relay network operators and see what can be done to get an estimated gas price based on the current network acceptance levels.

**Comment by RCasatta** [comment]
That is not correct, you calculated the price with the pre-sale value of ether.
As of today 1050000000000000 wei is around $0.008925 which is almost 1 cent per simple transaction.
As you said contract could become way more expensive.

**Comment by psionic81** [comment]
ah you're correct of course. we can definitely improve this, and our 1.0 is upcoming in a couple weeks.
