### ISSUE TITLE
Jaxx Open Source?

### ISSUE THREAD

**Issue by carsenk** [Jaxx-io/Jaxx#6]
Will the Jaxx wallet and apps be open sourced?

**Comment by fortran77** [comment]
Without access to source code, and without the ability to do a verified build from source, it is impossible to check if the wallet migh be stealing private keys. Even if the Jaxx wallet is not made fully open-sourced, at least the source code should be made available under a license that allows inspection and rebuilding.

**Comment by carsenk** [comment]
^^ Exactly. They have a small amount of code available on their site, but its really sketchy that they don't provide the full source to an HD wallet.

**Comment by kholbekj** [comment]
This is the step necessary for me to transfer any value to a Jaxx wallet. The provided js snippets (which is for some reason riddled with dead code and debug information..) is not nearly enough for me to trust the bundles.

**Comment by jonathancross** [comment]
Here is a copy of javascript source code they have on their website.

> Jaxx's code is now available to view below. This is the full code (minus third party libraries) of our wallet's back end; it does not contain any UI elements.

[jaxx-v1.1.3.txt](https://github.com/Jaxx-io/Jaxx/files/517808/jaxx-v1.1.3.txt)

**Comment by psionic81** [comment]
:) you can of course see the code by: right click->inspect, inside of the chrome plugin.

or don't run it even once, but download and go to the page:
chrome://plugins/

so you can do a directory search for the plugin files.

everything is done locally, so all of it must be there.

**Comment by fortran77** [comment]
It looks like source code, but it's an illusion. It's not source code in the common sense of the word.

I don't see any of the files that you usually find in a proper source distribution, e.g., a file called Makefile, INSTALL, Configure, etc. There are no build instructions. (Nor do they provide any way to do git clone, hg clone, svn checkout, etc.)

**Comment by jonathancross** [comment]
I agree with others that it would be good to have code for Android app, iOS app, etc. developed here on GitHub (issues, pull request, etc).  This is generally considered a requirement for modern, secure software, especially in the cryptocurrency space.  I found that JS on the jaxx.io website, but this is clearly not the source code for the mobile apps.

**Comment by psionic81** [comment]
Jaxx is wrapped in a shell+bridge+javascript on ios and android, and built with electron+javascript on desktop. (on all platforms, it's basically a wrapper plus the source of the chrome extension)


install instructions: javascript runs in the browser. double click index.html :D

**Comment by jonathancross** [comment]
Thanks for the reply @psionic81, are you able to submit the required code to this repo?  I only took a quick look, but there definitely seems to be functionality missing like creating a wallet, backing up seed, etc which is not part of `BTCBlockChainRelay`.

**Comment by Recmo** [comment]
And now this happened: https://vxlabs.com/2017/06/10/extracting-the-jaxx-12-word-wallet-backup-phrase/

Any basic code security review would have pointed this problem out.

**Comment by comodoro** [comment]
This is the biggest issue for me. I find it unbelievable that Jaxx is trusted by so many people with value yet is not fully open source.

**Comment by jarmo** [comment]
No answer from developers?

**Comment by Francewhoa** [comment]
Hi all :) We had the same question. We searched and found this answer from Decentral Inc. Which owns Jaxx.

> Jaxx is not open source, although the full code (minus UI) is visible on the website.
> 
> Much of the issues of cloned wallets that are surfacing recently are due to the code being easily available, copied and distributed. We do not desire clones of Jaxx (malicious or not) to be floating around. This leads to problems and confusion and we are trying to find a balance that's makes it difficult to take and distribute our code while still allowing it to be audited by those that wish to do so. 
> 
> In the interim, the Jaxx codebase is viewable on jaxx.io. You can also scrutinize the code for our Chrome extension by enabling Developer Mode, right-clicking anywhere on the app, and selecting Inspect. The Android .apk's code can be unpacked and scrutinized in full as well.

Source at https://decentral.zendesk.com/hc/en-us/articles/217877528-Is-Jaxx-Open-Source-

**Comment by Francewhoa** [comment]
@All :) For those interested to review part of the source code for Linux Jaxx wallet. You can review it by downloading the latest release at https://github.com/Jaxx-io/Jaxx/releases/

**Comment by kholbekj** [comment]
Thanks @Francewhoa for passing that quote on to here. This is of course not directed at you, but to anyone who might find their response reasonable, please think twice:

If the whole reason for hiding and obfuscating their source is that they don't want clones, either that means that their wallet does not work without some external component (otherwise anyone could copy the extension files and clone it anyway), or their vanguard against clones is so terribly executed that you should not trust them with your valuable assets anyway.

The logic is not even internally consistent.

**Comment by superduper** [comment]
@Francewhoa Source files you mentioned are empty. Tough luck.

**Comment by Francewhoa** [comment]
@superduper :) Interesting I though I saw something last time I checked

How about this alternative location?

> In the interim, the Jaxx codebase is viewable on [jaxx.io](https://jaxx.io/). You can also scrutinize the code for our Chrome extension by enabling Developer Mode, right-clicking anywhere on the app, and selecting **Inspect**. The Android .apk's code can be unpacked and scrutinized in full as well.

From https://decentral.zendesk.com/hc/en-us/articles/217877528-Is-Jaxx-Open-Source-

**Comment by jaxxThageesan** [comment]
You can view our compiled code base on our github repo.
