### ISSUE TITLE
Support bitcoin uri

### ISSUE THREAD

**Issue by plyoung** [Jaxx-io/Jaxx#9]
It is convenient when I can click on a link provided in the browser and it opens my wallet client with receiving address and perhaps even amount already filled out. Jaxx do not seem to support this. I've tried via both itch.io and onename.com and every time I had to use a different wallet app to handle the link.
https://bitcore.io/api/lib/uri

[edit] Just to be clear. I click on a link in the browser, choose a wallet app, and expect that wallet to receive the link and open up the send interface with address and amount filled out.

**Comment by jaxxThageesan** [comment]
@plyoung we partially support this feature know.  The bitcoin address field is populated when scanning the QR code.
